AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'test/test_helper.rb'
    - 'vendor/bundle/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 50

Style/Documentation:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
